---
version: "2.3"

services:
  app:
    image: "app"
    build:
      context: ..
      dockerfile: "app/Dockerfile"
    volumes:
      - ./app:/var/www/shared/app/app
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=app
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - FLASK_APP=app.main:app
      - FLASK_ENV=development
      - UWSGI_AUTORELOAD=1
    ports:
      - 8080:8080
    # healthcheck:
    #   test: curl http://localhost:8080/_mgmt/health
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      default: {}

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=app
    ports:
      - 5432:5432
    networks:
      default: {}
    healthcheck:
      test: pg_isready -d "app" -U "app"
networks:
  default:
    driver: bridge
