"""initial

Revision ID: 487e14461437
Revises: 
Create Date: 2021-09-28 15:32:01.251094+00:00

"""
# Ignores alembic style issues
# pylint: disable=invalid-name, missing-docstring
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "487e14461437"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.get_context().autocommit_block():
        op.create_table(
            "member",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=True,
            ),
            sa.Column("member_uuid", postgresql.UUID(), nullable=False),
            sa.Column("first_name", sa.String(length=64), nullable=True),
            sa.Column("last_name", sa.String(length=64), nullable=True),
            sa.Column("address", sa.String(length=64), nullable=True),
            sa.Column("email", sa.String(length=64), nullable=True),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("member_uuid"),
        )
        op.create_table(
            "card",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=True,
            ),
            sa.Column("member_uuid", postgresql.UUID(), nullable=False),
            sa.Column("date_activated", sa.DateTime(), nullable=True),
            sa.Column("is_current", sa.Boolean(), nullable=False),
            sa.ForeignKeyConstraint(
                ["member_uuid"],
                ["member.member_uuid"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_table(
            "transactions",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=True,
            ),
            sa.Column("card_id", sa.Integer(), nullable=False),
            sa.Column(
                "amount", sa.Numeric(precision=14, scale=2), nullable=False
            ),
            sa.Column("merchant", sa.String(length=255), nullable=True),
            sa.Column("category", sa.String(length=255), nullable=True),
            sa.Column("transaction_date", sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(
                ["card_id"],
                ["card.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    op.drop_table("card")
    op.drop_table("member")
    # ### end Alembic commands ###
